import Head from "next/head";
import { useRouter } from "next/router";
import styles from "@root/styles/View.module.css";

import Form from "@root/components/Form";
import useRequest from "@root/hooks/useClientSideRequest";
import { AuthServiceMethods, pages } from "@root/enums/index";

const Signin = () => {
  const router = useRouter();
  const url = router.pathname;

  const { doClientSideRequest, errors } = useRequest({
    method: AuthServiceMethods.SIGN_IN,
    onSuccess: () => router.push(`/${pages.HOME}`),
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Public</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.title}>Url: {url}</span>

        <div>
          <Form doClientSideRequest={doClientSideRequest} />
          {errors}
        </div>
      </main>
    </div>
  );
};

export default Signin;
