import Head from "next/head";
import { useRouter } from "next/router";
import styles from "@root/styles/View.module.css";

import LogoutButton from "@root/components/LogoutButton";
import withAuth from "@root/hoc/withAuth";
import { useSessionProviderContext } from "@root/contexts/sessionContext";

const Home = () => {
  const router = useRouter();
  const url = router.pathname;

  const { currentUser } = useSessionProviderContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.title}>Url: {url}</span>

        <p className={styles.description}>
          User: <span>{currentUser?.name}</span>
        </p>

        <div>
          <LogoutButton />
        </div>
      </main>
    </div>
  );
};

export default withAuth(Home);
