import Head from "next/head";
import { useRouter } from "next/router";
import styles from "@root/styles/View.module.css";

import LogoutButton from "@root/components/LogoutButton";
import { useSessionProviderContext } from "@root/contexts/sessionContext";

const Public = () => {
  const router = useRouter();
  const url = router.pathname;

  const { currentUser } = useSessionProviderContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Public</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.title}>Url: {url}</span>

        <div className={styles.description}>
          {currentUser?.name ? (
            <p>
              {" "}
              User: <span>{currentUser?.name}</span>
            </p>
          ) : (
            <p>Welcome</p>
          )}
        </div>

        <div>
          <LogoutButton />
        </div>
      </main>
    </div>
  );
};

export default Public;
